import type { AgentConfig } from "@/types/agent";
import { TUSDM_UNIT } from "@/lib/constants";

export const AGENT_CONFIGS: AgentConfig[] = [
  {
    id: "ceo",
    name: "CEO",
    role: "ceo",
    avatar: "/agents/ceo.png",
    description: "Chief Executive Officer — orchestrates the entire software company",
    systemPrompt: "ceo-system",
    model: "gpt-4o-mini",
    temperature: 0.7,
    maxTokens: 4096,
    fee: 500_000,
    capabilities: ["project-analysis", "task-decomposition", "orchestration", "quality-review"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "orchestration", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["orchestration", "project-management", "ai-software-company"],
      pricing: { amount: 500_000, unit: TUSDM_UNIT },
      requestsPerHour: 100,
    },
  },
  {
    id: "research",
    name: "Researcher",
    role: "research",
    avatar: "/agents/research.png",
    description: "Deep research on project requirements, technologies, and best practices",
    systemPrompt: "research-system",
    model: "gpt-4o-mini",
    temperature: 0.8,
    maxTokens: 4096,
    fee: 300_000,
    capabilities: ["web-research", "technology-analysis", "risk-assessment"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "research", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["research", "analysis", "technology-assessment"],
      pricing: { amount: 300_000, unit: TUSDM_UNIT },
      requestsPerHour: 200,
    },
  },
  {
    id: "architecture",
    name: "Architect",
    role: "architecture",
    avatar: "/agents/architecture.png",
    description: "Designs system architecture, component hierarchy, and data flow",
    systemPrompt: "architecture-system",
    model: "gpt-4o-mini",
    temperature: 0.6,
    maxTokens: 4096,
    fee: 400_000,
    capabilities: ["system-design", "component-modeling", "data-flow-design"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "system-architecture", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["architecture", "system-design", "component-modeling"],
      pricing: { amount: 400_000, unit: TUSDM_UNIT },
      requestsPerHour: 100,
    },
  },
  {
    id: "contract-engineer",
    name: "Contract Engineer",
    role: "contract-engineer",
    avatar: "/agents/contract.png",
    description: "Develops secure, optimized Aiken smart contracts",
    systemPrompt: "contract-engineer-system",
    model: "gpt-4o-mini",
    temperature: 0.5,
    maxTokens: 8192,
    fee: 600_000,
    capabilities: ["aiken-development", "contract-optimization", "validation"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "smart-contract-development", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["aiken", "smart-contracts", "cardano", "plutus"],
      pricing: { amount: 600_000, unit: TUSDM_UNIT },
      requestsPerHour: 50,
    },
  },
  {
    id: "frontend-engineer",
    name: "Frontend Engineer",
    role: "frontend-engineer",
    avatar: "/agents/frontend.png",
    description: "Builds responsive, modern frontend interfaces",
    systemPrompt: "frontend-engineer-system",
    model: "gpt-4o-mini",
    temperature: 0.7,
    maxTokens: 4096,
    fee: 400_000,
    capabilities: ["react-development", "ui-design", "api-integration"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "frontend-development", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["frontend", "react", "ui", "nextjs"],
      pricing: { amount: 400_000, unit: TUSDM_UNIT },
      requestsPerHour: 100,
    },
  },
  {
    id: "security-engineer",
    name: "Security Engineer",
    role: "security-engineer",
    avatar: "/agents/security.png",
    description: "Audits code, finds vulnerabilities, ensures best security practices",
    systemPrompt: "security-engineer-system",
    model: "gpt-4o-mini",
    temperature: 0.4,
    maxTokens: 4096,
    fee: 500_000,
    capabilities: ["security-audit", "vulnerability-detection", "penetration-testing"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "security-audit", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["security", "audit", "vulnerability", "smart-contract-security"],
      pricing: { amount: 500_000, unit: TUSDM_UNIT },
      requestsPerHour: 50,
    },
  },
  {
    id: "qa-engineer",
    name: "QA Engineer",
    role: "qa-engineer",
    avatar: "/agents/qa.png",
    description: "Creates test plans, writes test cases, ensures quality",
    systemPrompt: "qa-engineer-system",
    model: "gpt-4o-mini",
    temperature: 0.5,
    maxTokens: 4096,
    fee: 250_000,
    capabilities: ["test-planning", "test-case-generation", "coverage-analysis"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "quality-assurance", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["qa", "testing", "quality-assurance"],
      pricing: { amount: 250_000, unit: TUSDM_UNIT },
      requestsPerHour: 200,
    },
  },
  {
    id: "documentation-engineer",
    name: "Documentation Engineer",
    role: "documentation-engineer",
    avatar: "/agents/docs.png",
    description: "Writes comprehensive documentation and developer guides",
    systemPrompt: "documentation-engineer-system",
    model: "gpt-4o-mini",
    temperature: 0.6,
    maxTokens: 4096,
    fee: 200_000,
    capabilities: ["technical-writing", "api-documentation", "guide-creation"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "technical-writing", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["documentation", "technical-writing", "developer-guides"],
      pricing: { amount: 200_000, unit: TUSDM_UNIT },
      requestsPerHour: 200,
    },
  },
  {
    id: "deployment-engineer",
    name: "Deployment Engineer",
    role: "deployment-engineer",
    avatar: "/agents/deployment.png",
    description: "Prepares deployment scripts, configuration, and release checklists",
    systemPrompt: "deployment-engineer-system",
    model: "gpt-4o-mini",
    temperature: 0.5,
    maxTokens: 4096,
    fee: 350_000,
    capabilities: ["deployment-planning", "configuration-management", "ci-cd-setup"],
    contextWindow: 128000,
    masumi: {
      capability: { name: "deployment", version: "1.0.0" },
      author: { name: "Foundry", organization: "Foundry" },
      tags: ["deployment", "devops", "ci-cd", "configuration"],
      pricing: { amount: 350_000, unit: TUSDM_UNIT },
      requestsPerHour: 100,
    },
  },
];

export const AGENTS = AGENT_CONFIGS;
