"use client";

import { useState, useCallback } from "react";
import { motion } from "framer-motion";
import {
  FileOutput,
  Download,
  Eye,
  X,
  FileDown,
  Archive,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useProjectStore } from "@/store/project-store";

interface OutputsClientProps {
  projectId: string;
}

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadAll(outputs: ReturnType<typeof useProjectStore.getState>["outputs"]): void {
  const combined = outputs
    .map((o) => `# ${o.title}\n\n${o.content}\n\n---\n`)
    .join("\n");
  downloadBlob(combined, "all-outputs.md", "text/markdown");
}

export default function OutputsClient({ projectId }: OutputsClientProps) {
  const outputs = useProjectStore((s) =>
    s.outputs.filter((o) => o.projectId === projectId),
  );
  const [selectedOutput, setSelectedOutput] = useState<string | null>(null);

  const selected = selectedOutput
    ? outputs.find((o) => o.id === selectedOutput)
    : null;

  const grouped = outputs.reduce(
    (acc, o) => {
      if (!acc[o.type]) acc[o.type] = [];
      acc[o.type].push(o);
      return acc;
    },
    {} as Record<string, typeof outputs>,
  );

  const handleDownload = useCallback(
    (output: (typeof outputs)[number]) => {
      const ext = output.mimeType === "text/x-aiken" ? ".ak" : ".md";
      downloadBlob(output.content, output.title.replace(/\s+/g, "-") + ext, output.mimeType);
    },
    [],
  );

  const handleDownloadAll = useCallback(() => {
    downloadAll(outputs);
  }, [outputs]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-8"
    >
      <div className="flex flex-col gap-4 rounded-[1.5rem] border border-border bg-card p-6 shadow-[var(--shadow-card)] lg:flex-row lg:items-end lg:justify-between">
        <div className="flex items-center gap-2">
          <FileOutput className="h-6 w-6 text-primary" />
          <h1 className="text-2xl font-bold">Generated Outputs</h1>
          {outputs.length > 0 && (
            <Badge variant="outline" className="ml-2">
              {outputs.length} files
            </Badge>
          )}
        </div>
        <div className="space-y-2">
          <p className="text-sm text-foreground-muted">
            Project output artifacts generated by the agent company.
          </p>
          <p className="text-xs uppercase tracking-[0.2em] text-foreground-dim">
            Project {projectId}
          </p>
        </div>
        {outputs.length > 0 && (
          <Button variant="secondary" className="gap-2 lg:ml-auto" onClick={handleDownloadAll}>
            <Archive className="h-4 w-4" />
            Download All
          </Button>
        )}
      </div>

      {outputs.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-[1.5rem] border border-border bg-card py-24 text-center shadow-[var(--shadow-card)]">
          <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-3xl border border-border bg-background">
            <FileOutput className="h-10 w-10 text-foreground-muted" />
          </div>
          <h2 className="mb-2 text-xl font-semibold">No outputs generated</h2>
          <p className="max-w-md text-foreground-muted">
            Run an execution to generate project outputs. Results will appear here once agents complete their tasks.
          </p>
        </div>
      ) : (
        <div className="grid gap-8 lg:grid-cols-3">
          <div className="lg:col-span-2 space-y-6">
            {Object.entries(grouped).map(([type, typeOutputs]) => (
              <div key={type}>
                <h3 className="text-sm font-medium text-foreground-muted uppercase tracking-wider mb-3">
                  {type} ({typeOutputs.length})
                </h3>
                <div className="space-y-2">
                  {typeOutputs.map((output) => (
                    <div
                      key={output.id}
                      className={`rounded-2xl border p-4 transition-colors duration-200 ${
                        selectedOutput === output.id
                          ? "border-primary/30 bg-primary/5"
                          : "border-border bg-card hover:border-border-hover hover:bg-surface"
                      }`}
                    >
                      <div className="flex items-center justify-between">
                        <button
                          onClick={() => setSelectedOutput(output.id)}
                          className="flex-1 text-left"
                        >
                          <span className="text-sm font-medium text-foreground block">
                            {output.title}
                          </span>
                          <span className="text-xs text-foreground-muted mt-0.5 block">
                            {new Date(output.createdAt).toLocaleDateString()}
                          </span>
                          {output.sourceAgentRole && (
                            <Badge variant="outline" className="mt-2 text-[10px] px-1.5 py-0">
                              {output.sourceAgentRole.replace(/-/g, " ")}
                            </Badge>
                          )}
                        </button>
                        <div className="flex gap-1 shrink-0">
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => setSelectedOutput(output.id)}
                          >
                            <Eye className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => handleDownload(output)}
                          >
                            <FileDown className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="lg:col-span-1">
            {selected ? (
              <div className="sticky top-8 rounded-[1.5rem] border border-border bg-card p-6 shadow-[var(--shadow-card)]">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-sm font-semibold">{selected.title}</h3>
                  <button
                    type="button"
                    onClick={() => setSelectedOutput(null)}
                    className="btn-icon btn-icon--sm"
                    aria-label="Close preview"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
                <Badge variant="outline" className="mb-4">
                  {selected.type}
                </Badge>
                <div className="mb-4 max-h-[60vh] overflow-y-auto rounded-2xl border border-border bg-background p-4">
                  <pre className="text-xs text-foreground-muted whitespace-pre-wrap font-mono">
                    {selected.content}
                  </pre>
                </div>
                <Button
                  variant="default"
                  size="sm"
                  className="btn--block"
                  onClick={() => handleDownload(selected)}
                >
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              </div>
            ) : (
              <div className="sticky top-8 rounded-[1.5rem] border border-border bg-card p-6 text-center shadow-[var(--shadow-card)]">
                <Eye className="h-8 w-8 text-foreground-muted mx-auto mb-2" />
                <p className="text-sm text-foreground-muted">
                  Select an output to preview
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </motion.div>
  );
}
